services:
  postgres:
    image: postgres:latest
    container_name: kpz-kanban-postgresdb
    ports:
      - "${DB_PORT}:5432"
    environment:
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: