CREATE TYPE "project_member_roles" AS ENUM (
  'OWNER',
  'ADMIN',
  'MEMBER',
  'VIEWER'
);

CREATE TYPE "kanban_task_priorities" AS ENUM (
  'HIGH',
  'MEDIUM',
  'LOW',
  'OPTIONAL'
);

CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar(32),
    "email" text UNIQUE NOT NULL,
    "password_hash" text NOT NULL
);

CREATE TABLE "projects" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(255) NOT NULL,
    "description" text,
    "owner_id" int NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "project_members" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" int NOT NULL,
    "user_id" int NOT NULL,
    "role" project_member_roles NOT NULL DEFAULT 'MEMBER',
    UNIQUE ("project_id", "user_id")
);

CREATE TABLE "kanban_boards" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" int NOT NULL,
    "title" varchar(255) NOT NULL,
    "description" text,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "kanban_columns" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "board_id" int NOT NULL,
    "title" varchar(255) NOT NULL,
    "position" int NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "kanban_tasks" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "column_id" int NOT NULL,
    "title" varchar(255) NOT NULL,
    "description" text,
    "position" int NOT NULL,
    "priority" kanban_task_priorities DEFAULT 'MEDIUM',
    "due_date" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "projects" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "project_members" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "kanban_boards" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "kanban_columns" ADD FOREIGN KEY ("board_id") REFERENCES "kanban_boards" ("id");

ALTER TABLE "kanban_tasks" ADD FOREIGN KEY ("column_id") REFERENCES "kanban_columns" ("id");